# Generated by Django 2.2.7 on 2019-11-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_auto_20191123_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='UrlDetail',
        ),
        migrations.RenameField(
            model_name='urldetail',
            old_name='httpurl',
            new_name='http_main_url',
        ),
        migrations.RenameField(
            model_name='urldetail',
            old_name='short_id',
            new_name='short_url_id',
        ),
    ]
